actions:
- command: deploy_linaro_android_image
  parameters:
    images:
    - partition: 'ptable'
      url: 'http://builds.96boards.org/snapshots/hikey/linaro/uefi/latest/ptable-linux-4g.img'
    - partition: 'boot'
      url: '${BOOT_URL}'
    - partition: 'system'
      url: '${SYSTEM_URL}'
    target_type: 'ubuntu'
- command: boot_linaro_image
- command: 'lava_command_run'
  parameters:
    commands:
    - 'nmcli dev status'
    - 'nmcli dev wifi'
    - 'nmcli dev wifi con LAVA_Leased password RedDwarf name LAVA_Leased'
    - 'nmcli con up id LAVA_Leased'
    - '/sbin/iw wlan0 set power_save off'
    - 'echo 0 > /sys/kernel/debug/ieee80211/phy0/wlcore/sleep_auth'
    - 'ping -c 4 google.com'
- command: 'lava_command_run'
  parameters:
    commands:
    - '/sbin/sgdisk -e /dev/mmcblk0'
    - '/sbin/parted /dev/mmcblk0 resizepart 9 Yes 100%'
    - '/sbin/resize2fs /dev/disk/by-label/rootfs'
    - 'df -h'
- command: submit_results
  parameters:
    server: 'http://${LAVA_SERVER}'
    stream: '${BUNDLE_STREAM_NAME}'
device_type: '${DEVICE_TYPE}'
job_name: '${BUILD_URL}'
timeout: 18000
