actions:
- command: deploy_linaro_image
  parameters:
    bootloadertype: 'uefi'
    customize:
      '${STARTUP_NSH}':
      - 'boot:/EFI/BOOT/startup.nsh'
    hwpack: '${HWPACK_BUILD_URL}'
    rootfs: '${ROOTFS_BUILD_URL}'
  metadata:
    distribution: 'openembedded'
    hwpack.build: '${BUILD_NUMBER}'
    hwpack.type: '${hwpack_type}'
    rootfs.build: '${ROOTFS_BUILD_NUMBER}'
    rootfs.type: '${rootfs_type}'
    git URL: '${GIT_URL}'
    git branch: '${GIT_BRANCH}'
    git commit: '${GIT_COMMIT}'
- command: lava_test_shell
  parameters:
    timeout: 7200
    testdef_repos:
    - git-repo: git://git.linaro.org/qa/test-definitions.git
      parameters:
        TST_CMDFILES: syscalls
        SKIPFILE: '${KERNEL_URL}/skipfile-ilp32'
      testdef: openembedded/ltp.yaml
- command: submit_results
  parameters:
    server: 'http://${LAVA_SERVER}'
    stream: '${BUNDLE_STREAM_NAME}'
device_type: '${DEVICE_TYPE}'
job_name: '${BUILD_URL}'
timeout: 18000
