actions:
- command: deploy_linaro_kernel
  parameters:
    dtb: '${DTB_URL}/hip04-d01.dtb'
    kernel: '${KERNEL_URL}/zImage'
    nfsrootfs: '${ROOTFS_BUILD_URL}'
  metadata:
    distribution: 'openembedded'
    hwpack.build: '${BUILD_NUMBER}'
    hwpack.type: '${hwpack_type}'
    rootfs.build: '${ROOTFS_BUILD_NUMBER}'
    rootfs.type: 'minimal-armv7a-gcc-4.9'
    git URL: '${GIT_URL}'
    git branch: '${GIT_BRANCH}'
    git commit: '${GIT_COMMIT}'
- command: boot_linaro_image
- command: lava_test_shell
  parameters:
    testdef_repos:
    - git-repo: 'git://git.linaro.org/qa/test-definitions.git'
      testdef: 'common/coresight-test.yaml'
    timeout: 1800
- command: submit_results
  parameters:
    server: 'http://${LAVA_SERVER}'
    stream: '${BUNDLE_STREAM_NAME}'
device_type: '${DEVICE_TYPE}'
job_name: '${BUILD_URL}'
timeout: 3600
