{% extends device_type %}

{% set job_timeout = 120 %}
{% block metadata %}
  {{ super() }}
{% endblock metadata %}

{% block job_name %}lt-qcom-{{OS_INFO}}-main-{{BUILD_NUMBER}}{% endblock job_name %}

{% block test_target %}
  {{ super() }}
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/smoke/smoke.yaml
      params:
              TESTS: {{SMOKE_TESTS}}
      name: linux-smoke
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/usb-smoke/usb-smoke-test.yaml
      name: linux-usb-smoke
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/toolchain-smoke/toolchain-smoke.yaml
      name: linux-toolchain-smoke
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/device-tree/device-tree.yaml
      name: linux-device-tree
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/meminfo/meminfo.yaml
      name: meminfo

    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/dd-wr-speed/dd-wr-speed.yaml
      name: linux-dd-wr-speed
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/sysbench/sysbench.yaml
      params:
              NUM_THREADS: 4
              TESTS: cpu memory threads mutex
      name: linux-sysbench
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/device-read-perf/device-read-perf.yaml
      name: linux-device-read-perf
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/hackbench/hackbench.yaml
      name: linux-hackbench
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/linpack/linpack.yaml
      name: linux-linpack
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/openssl/openssl-speed.yaml
      name: linux-openssl-speed
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/stream/stream-uniprocessor.yaml
      name: linux-stream-uniprocessor
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/pi-stress/pi-stress.yaml
      name: linux-pi-stress

    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/pm-qa/pm-qa.yaml
      name: linux-pm-qa
      params:
        TESTS: {{PM_QA_TESTS}}

    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/docker/docker.yaml
      name: linux-containers
{% endblock test_target %}
