actions:
- command: deploy_linaro_image
  parameters:
    hwpack: '${HWPACK_BUILD_URL}'
    rootfs: '${ROOTFS_BUILD_URL}'
  metadata:
    build id: '${BUILD_NUMBER}'
    defconfig: '${defconfig}'
    git URL: '${GIT_URL}'
    git branch: '${GIT_BRANCH}'
    git commit: '${GIT_COMMIT}'
- command: boot_linaro_image
  parameters:
    boot_cmds:
      - 'expect Start:'
      - 'sendline 3'
      - 'expect Choice:'
      - 'sendline 3'
      - 'expect Delete entry:'
      - 'sendline 1'
      - 'expect Choice:'
      - 'sendline 1'
      - 'expect Select the Boot Device:'
      - 'sendline 6'
      - 'expect File path of the EFI Application or the kernel:'
      - 'sendline uImage'
      - 'expect Has FDT support? [y/n]'
      - 'sendline y'
      - 'expect Add an initrd: [y/n]'
      - 'sendline n'
      - 'expect Arguments to pass to the binary:'
      - 'sendcontrol M'
      - 'expect Description for this new Entry:'
      - 'sendline LAVA Test Image'
      - 'expect Choice:'
      - 'sendline 2'
      - 'expect Update entry:'
      - 'sendline 1'
      - 'expect File path of the EFI Application or the kernel:'
      - 'sendcontrol M'
      - 'expect Has FDT support? [y/n]'
      - 'sendline y'
      - 'expect Add an initrd: [y/n]'
      - 'sendline n'
      - 'expect Arguments to pass to the binary:'
      - 'sendline console=tty0 console=ttyAMA0,38400n8 root=/dev/sda1 rootwait ro'
      - 'expect Description for this new Entry:'
      - 'sendcontrol M'
      - 'expect Choice:'
      - 'sendline 4'
      - 'expect Select the Boot Device:'
      - 'sendline 6'
      - 'expect File path of the FDT blob:'
      - 'sendline v2p-ca15-tc2.dtb'
      - 'expect Choice:'
      - 'sendline 5'
      - 'expect Start:'
      - 'sendline 1'
- command: lava_test_shell
  parameters:
    testdef_repos:
    - git-repo: git://git.linaro.org/qa/test-definitions.git
      testdef: ubuntu/pwrmgmt.yaml
    timeout: 1200
- command: lava_test_shell
  parameters:
    testdef_repos:
    - git-repo: git://git.linaro.org/qa/test-definitions.git
      testdef: ubuntu/smoke-tests-basic.yaml
    timeout: 1200
- command: submit_results
  parameters:
    server: 'http://${LAVA_SERVER}'
    stream: '${BUNDLE_STREAM_NAME}'
device_type: '${DEVICE_TYPE}'
job_name: '${BUILD_URL}'
timeout: 3600