actions:
  - command: deploy_linaro_image
    parameters:
      bootloadertype: 'uefi'
      customize:
        'boot:/fvp':
        - 'delete'
        '${STARTUP_NSH}':
        - 'boot:/EFI/BOOT/startup.nsh'
        '${BL1_URL}':
        - 'boot:/fvp_bl1.bin'
        '${FIP_URL}':
        - 'boot:/fvp_fip.bin'
        'http://people.linaro.org/~fu.wei/LAVA/test/UEFI/uefi_update_capsule/uefi_update_capsule_example_v2.txt':
        - 'rootfs:/uefi_update_capsule_example.txt'
      image: '${IMAGE_URL}'
      metadata:
        build id: '${BUILD_NUMBER}'
        git URL: '${GIT_URL}'
        git branch: '${GIT_BRANCH}'
        git commit: '${GIT_COMMIT}'
        template: 'update-capsule'
  - command: boot_linaro_image
    parameters:
      boot_cmds:
      - 'sendline 2'
      - 'expect or any other key to continue.'
      - 'sendline '
  - command: lava_test_shell
    parameters:
      testdef_repos:
      - parameters:
          EXAMPLE_FILE_URL: '/uefi_update_capsule_example.txt'
        url: 'http://people.linaro.org/~fu.wei/LAVA/test/UEFI/uefi_update_capsule/uefi_update_capsule_temp.yaml'
  - command: submit_results
    parameters:
      server: 'http://${LAVA_SERVER}'
      stream: '${BUNDLE_STREAM_NAME}'
device_type: '${DEVICE_TYPE}'
job_name: '${BUILD_URL}'
timeout: 18000
