- job:
    name: trigger-openembedded-lkft-developer-ci-${DEVELOPER_JOB_NAME}
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 30
    parameters:
        - string:
            name: KERNEL_BRANCH
            default: '${KERNEL_BRANCH}'
    disabled: false
    node: master
    display-name: 'Trigger for LKFT - developer CI for ${DEVELOPER_JOB_NAME}'
    scm:
        - git:
            url: ${KERNEL_REPO}
            refspec: +refs/heads/${KERNEL_BRANCH}:refs/remotes/origin/${KERNEL_BRANCH}
            name: origin
            branches:
                - origin/${KERNEL_BRANCH}
            skip-tag: true
            shallow-clone: false
            wipe-workspace: false
    triggers:
        - pollscm:
            cron: 'H/5 * * * *'
    wrappers:
        - timestamps
        - build-name:
            name: '#${BUILD_NUMBER}-${GIT_REVISION,length=8}'
    builders:
        - shell: |
            #!/bin/bash -e
            git clean -fdx
            MAKE_KERNELVERSION=$(make kernelversion)
            KERNEL_VERSION=$(echo ${MAKE_KERNELVERSION} | cut -f1,2 -d'.')
            echo KERNEL_DESCRIBE=$(git describe --always) >> lkft_parameters
            echo SRCREV_kernel=${GIT_COMMIT} >> lkft_parameters
            echo MAKE_KERNELVERSION=${MAKE_KERNELVERSION} >> lkft_parameters
            echo KERNEL_VERSION=${KERNEL_VERSION} >> lkft_parameters
            cat lkft_parameters
    publishers:
        - trigger-parameterized-builds:
            - project:
                - 'openembedded-lkft-developer-ci-${DEVELOPER_JOB_NAME}'
              condition: SUCCESS
              property-file: lkft_parameters
