{% extends device_type %}

{% set job_timeout = 90 %}

{% block job_name %}{{JOB_NAME}}-{{ANDROID_META_BUILD}}-optee-gtest-kmgk{% endblock job_name %}
{% block priority %}75{% endblock priority %}

{% block test_target %}
{{ super() }}
- test:
      namespace: tlxc
      timeout:
        minutes: {% if job_timeout is defined %}{{ job_timeout-5|int|abs }}{% else %}300{% endif %}
      definitions:
        - repository: https://github.com/Linaro/test-definitions.git
          from: git
          path: automated/android/optee/optee-gtest-kmgk.yaml
          name: optee-gtest-kmgk
{% endblock test_target %}
