{% extends device_type %}

{% set job_timeout = 150 %}

{% block job_name %}{{JOB_NAME}}-{{ANDROID_META_BUILD}}-monkey{% endblock job_name %}
{% block priority %}75{% endblock priority %}

{% block test_target %}
{{ super() }}
- test:
      namespace: tlxc
      timeout:
        minutes: 120
      definitions:
        - repository: https://git.linaro.org/qa/test-definitions.git
          from: git
          path: automated/android/monkey/monkey.yaml
          params:
            MONKEY_PARAMS: "-s 1520023612672 --pct-syskeys 0 -p com.android.settings --monitor-native-crashes"
            EVENT_COUNT: 600000
            BLACKLIST: ""
          name: monkey
{% endblock test_target %}
