context:
  test_character_delay: 10

device_type: x86
job_name: optee-xtest-qemu-${BUILD_NUMBER}
timeouts:
  job:
    minutes: 30
  action:
    minutes: 10
  connection:
    minutes: 2
priority: medium
visibility: public

metadata:
  git branch: ${GIT_BRANCH}
  git repo: ${GIT_URL}
  git commit: ${GIT_COMMIT}
  build url: ${BUILD_URL}
  build location: ${PUBLISH_SERVER}${PUB_DEST}

actions:
- deploy:
    timeout:
      minutes: 15
    to: tftp
    kernel:
      url: http://snapshots.linaro.org/openembedded/lkft/morty/intel-core2-32/rpb/linux-mainline/355/bzImage--4.13+git0+33d930e59a-r0-intel-core2-32-20171016062623-355.bin
    modules:
      url: http://snapshots.linaro.org/openembedded/lkft/morty/intel-core2-32/rpb/linux-mainline/355/modules--4.13+git0+33d930e59a-r0-intel-core2-32-20171016062623-355.tgz
      compression: gz
    nfsrootfs:
      url: http://snapshots.linaro.org/openembedded/lkft/morty/intel-core2-32/rpb/linux-mainline/355/rpb-console-image-intel-core2-32-20171016062623-355.rootfs.tar.xz
      compression: xz
    os: oe

- boot:
    timeout:
      minutes: 10
    method: ipxe
    commands: nfs
    parameters:
      shutdown-message: "reboot: Restarting system"
    auto_login:
      login_prompt: 'login:'
      username: root
      login_commands:
        - su
    prompts:
    - 'root@intel-core2-32:'

- test:
    timeout:
      minutes: 30
    definitions:
    - repository: git://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/optee/optee-xtest-qemu.yaml
      name: optee-xtest
      parameters:
        PUBLISH_DEST: ${PUBLISH_SERVER}${PUB_DEST}

notify:
    recipients:
    - to:
        method: email
        email: joakim.bech@linaro.org
    criteria:
        status: complete
    verbosity: verbose
