- job:
    name: aes-openembedded-rpb-sumo
    project-type: matrix
    defaults: global
    logrotate:
        daysToKeep: 30
        numToKeep: 30
        artifactNumToKeep: 1
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
                - job-workspace
            loic.poulain@linaro.org:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
            ryan.harkin@linaro.org:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
    parameters:
        - string:
            name: IMAGES
            default: 'rpb-console-image-aes rpb-console-image-aes-dev'
        - string:
            name: IMAGES_RPB
            default: ''
        - string:
            name: IMAGES_RPB_WAYLAND
            default: ''
        - string:
            name: MANIFEST_URL
            default: 'https://github.com/96boards/oe-rpb-manifest.git'
        - string:
            name: MANIFEST_BRANCH_PREFIX
            default: 'aes/'
        - string:
            name: MANIFEST_BRANCH
            default: 'sumo'
        - string:
            name: BASE_URL
            default: 'https://snapshots.linaro.org/'
        - string:
            name: LAVA_SERVER
            default: 'https://validation.linaro.org/RPC2/'
        - string:
            name: STAGING_LAVA_SERVER
            default: 'https://staging.validation.linaro.org/RPC2/'
        - string:
            name: QA_SERVER
            default: 'https://qa-reports.linaro.org'
        - string:
            name: AUTH_GROUPS
            default: 'linaro, sse-team, aes-team'
    disabled: false
    node: master
    display-name: 'AES OpenEmbedded RPB (sumo)'
    axes:
        - axis:
            type: user-defined
            name: MACHINE
            values:
                - 'aes410'
        - axis:
            type: user-defined
            name: DISTRO
            values:
                - rpb
        - axis:
            type: slave
            name: label
            values:
                - docker-stretch-amd64
    execution-strategy:
        sequential: false
    wrappers:
        - timestamps
        - ssh-agent-credentials:
            users:
                - '768c1ba1-6052-4b97-a531-7e4fabda6979'
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: QA_REPORTS_TOKEN
    builders:
        - shell: |
            #!/bin/bash

            # some machine names we use on 96boards are slightly different
            case "${MACHINE}" in
              dragonboard-410c)
                MACHINE=dragonboard410c
                ;;
              dragonboard-820c)
                MACHINE=dragonboard820c
                ;;
            esac

            echo "PUB_DEST=openembedded/aes/${MANIFEST_BRANCH}/${MACHINE}/${BUILD_NUMBER}/${DISTRO}" > pub_dest_parameters
        - inject:
            properties-file: pub_dest_parameters
        - shell:
            !include-raw: rpb-openembedded/builders.sh
        - inject:
            properties-file: post_build_lava_parameters
        - linaro-publish-token
        - shell:
            !include-raw: rpb-openembedded/buildinfo-protected.sh
        - shell:
            !include-raw: rpb-openembedded/publishers.sh
        - shell:
            !include-raw: lt-qcom-openembedded/submit_for_testing.sh
    publishers:
        - groovy-postbuild:
            script:
                !include-raw:
                  - rpb-openembedded/postbuild.groovy
                  - openembedded-lkft/postbuild.groovy
        - email-ext:
            recipients: 'fathi.boudra@linaro.org, loic.poulain@linaro.org, ryan.harkin@linaro.org'
            always: true
            matrix-trigger: only-parent
