- job:
    name: android-lcr-reference-x15-o
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 60
            num-to-keep: 60
    parameters:
        - string:
            name: ART_URL
            default: https://android-qa-reports.linaro.org/api/
        - string:
            name: BUILD_DIR
            default: r-lcr-oreo
        - string:
            name: QA_SERVER
            default: 'https://qa-reports.linaro.org'
        - string:
            name: QA_SERVER_PROJECT
            default: 'lcr-reference-x15-o'
    disabled: true
    node: docker-xenial-aosp
    display-name: 'Reference LCR Android O build for X15'
    concurrent: true
    triggers:
        - gerrit:
            server-name: __ANY__
            trigger-on:
                - change-merged-event
            projects:
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android-patchsets'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'master'
                  file-paths:
                      - compare-type: 'PLAIN'
                        pattern: 'x15-o-workarounds'
                      - compare-type: 'PLAIN'
                        pattern: 'O-RLCR-PATCHSET'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'device/linaro/common'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'platform/manifest'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                  file-paths:
                      - compare-type: 'PLAIN'
                        pattern: 'x15.xml'
                      - compare-type: 'PLAIN'
                        pattern: 'linaro.xml'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android-build-configs'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'master'
                  file-paths:
                      - compare-type: 'PLAIN'
                        pattern: 'lcr-reference-x15-o'
    wrappers:
        - timestamps
        - timeout:
            timeout: 500
        - ssh-agent-credentials:
                users:
                    - '768c1ba1-6052-4b97-a531-7e4fabda6979'
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: QA_REPORTS_TOKEN
            - text:
                credential-id: ARTIFACTORIAL_TOKEN
                variable: ARTIFACTORIAL_TOKEN
    builders:
        !include: android-lcr/x15/builders-v2-jinja2.yaml.inc
    publishers:
        !include: android-lcr/common/publishers.yaml.inc
