- job:
    name: android-lcr-reference-x15-o-premerge-ci
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 60
            num-to-keep: 60
    parameters:
        - string:
            name: ART_URL
            default: https://android-qa-reports.linaro.org/api/
        - string:
            name: BUILD_DIR
            default: r-lcr-oreo
        - string:
            name: BUILD_CONFIG_FILENAME
            default: lcr-reference-x15-o
        - string:
            name: QA_SERVER
            default: 'https://qa-reports.linaro.org'
        - string:
            name: QA_SERVER_PROJECT
            default: 'lcr'
    disabled: false
    node: docker-xenial-aosp
    display-name: 'Premerge CI job to test patch for X15 R-LCR'
    concurrent: true
    triggers:
        - gerrit:
            override-votes: true
            gerrit-build-successful-verified-value: 1
            gerrit-build-failed-verified-value: -1
            trigger-on:
                - comment-added-contains-event:
                    comment-contains-value: '.*RunPremergeX15Tests.*'
            server-name: __ANY__
            projects:
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android-patchsets'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'master'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'device/linaro/common'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'platform/manifest'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android-build-configs'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'master'
    wrappers:
        - timestamps
        - timeout:
            timeout: 500
        - ssh-agent-credentials:
                users:
                    - '768c1ba1-6052-4b97-a531-7e4fabda6979'
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: QA_REPORTS_TOKEN
            - text:
                credential-id: ARTIFACTORIAL_TOKEN
                variable: ARTIFACTORIAL_TOKEN
    builders:
        !include: android-lcr/x15/builders-v2-jinja2.yaml.inc
    publishers:
        !include: android-lcr/common/publishers.yaml.inc
