- scm:
    name: kernel
    scm:
        - git:
            url: git://git.linaro.org/landing-teams/working/arm/kernel-release.git
            branches:
                - origin/lsk-3.18-armlt
            skip-tag: true
            shallow-clone: true
            wipe-workspace: false
- scm:
    name: firmware
    scm:
        - git:
            url: git://git.linaro.org/arm/vexpress-firmware.git
            branches:
                - origin/juno-recovery-tarball
            skip-tag: true
            shallow-clone: true
            wipe-workspace: false
- job:
    name: android-lcr-reference-juno-o
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 60
            num-to-keep: 60
    parameters:
        - string:
            name: ART_URL
            default: https://android-qa-reports.linaro.org/api/
        - string:
            name: BUILD_DIR
            default: r-lcr-oreo
        - string:
            name: BUILD_CONFIG_FILENAME
            default: lcr-reference-juno-p
    disabled: false
    node: docker-xenial-aosp
    display-name: 'Reference LCR Android O Build for Juno'
    concurrent: true
    scm:
        - kernel
        - firmware
    triggers:
        - pollscm: "H/5 * * * *"
        - gerrit:
            server-name: __ANY__
            trigger-on:
                - change-merged-event
            projects:
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android-patchsets'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'master'
                  file-paths:
                      - compare-type: 'PLAIN'
                        pattern: 'O-RLCR-PATCHSET'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'device/linaro/common'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'platform/manifest'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                  file-paths:
                      - compare-type: 'PLAIN'
                        pattern: 'arm.xml'
                      - compare-type: 'PLAIN'
                        pattern: 'linaro.xml'
                      - compare-type: 'PLAIN'
                        pattern: 'optee.xml'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android/device/linaro/juno'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'linaro-oreo'
                - project-compare-type: 'PLAIN'
                  project-pattern: 'android-build-configs'
                  branches:
                      - branch-compare-type: 'PLAIN'
                        branch-pattern: 'master'
                  file-paths:
                      - compare-type: 'PLAIN'
                        pattern: 'lcr-reference-juno-p'
    wrappers:
        - timestamps
        - timeout:
            timeout: 500
    builders:
        !include: android-lcr/juno/builders.yaml.inc
    publishers:
        !include: android-lcr/common/publishers.yaml.inc
