- job:
    name: bhoj-test
    project-type: freestyle
    defaults: global
    logrotate:
        daysToKeep: 30
        numToKeep: 30
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            vishal.bhoj@linaro.org:
                - job-build
                - job-read
                - job-extended-read
                - job-configure
                - job-cancel
    disabled: false
    node: master
    display-name: 'Trigger for LKFT HiKey builds (4.4 branch)'
    wrappers:
        - timestamps
        - credentials-binding:
            - text:
                credential-id: JJB_USER
                variable: JJB_USER
        - credentials-binding:
            - text:
                credential-id: JJB_PASSWORD
                variable: JJB_PASSWORD
        - credentials-binding:
            - text:
                credential-id: LAVA_USER
                variable: LAVA_USER
        - credentials-binding:
            - text:
                credential-id: LAVA_TOKEN
                variable: LAVA_TOKEN
        - credentials-binding:
            - text:
                credential-id: LT_QCOM_KEY
                variable: LT_QCOM_KEY
        - credentials-binding:
            - text:
                credential-id: AUTH_TOKEN
                variable: AUTH_TOKEN
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: SQUAD_AUTH_TOKEN
        - build-name:
            name: '#${BUILD_NUMBER}-${GIT_REVISION,length=8}'
    builders:
        - shell: |
            #!/bin/bash -e
            exit 1
    publishers:
       - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                - FAILURE 
              build-steps:
                - shell: |
                   #!/bin/bash -e
                   curl --header "Auth-Token: ${QA_REPORTS_TOKEN}" --form tests='{"build_process/build": "pass"}'  ${qa_server}/api/submit/${qa_server_team}/${qa_server_project}/${QA_BUILD_VERSION}/${TEST_DEVICE_TYPE}
