- job:
    name: ddiaz-aosp
    project-type: freestyle
    defaults: global
    logrotate:
        daysToKeep: 60
        numToKeep: 60
    properties:
        - authorization:
            anonymous:
                - job-read
            daniel.diaz@linaro.org:
                - job-build
                - job-read
                - job-extended-read
                - job-configure
                - job-cancel
    disabled: false
    node: docker-lkft-new
    display-name: 'AOSP build playground for Daniel Diaz'
    concurrent: true
    wrappers:
        - timestamps
        - timeout:
            timeout: 500
    builders:
        - shell: |
            #!/bin/bash

            env
            echo "Hello, world!"
    publishers:
        - email:
            recipients: 'daniel.diaz@linaro.org'
