- job:
    name: ddiaz-test
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
            linaro:
                - job-build
                - job-cancel
            daniel.diaz@linaro.org:
                - job-build
                - job-read
                - job-extended-read
                - job-configure
                - job-cancel
        - build-discarder:
            days-to-keep: 60
            num-to-keep: 60
    disabled: false
    node: master
    display-name: 'Test job for Daniel Diaz'
    builders:
        - shell: |
            #!/bin/bash

            env
            echo "Hello, world!"
    publishers:
        - email:
            recipients: 'daniel.diaz@linaro.org'
