- job:
    name: leg-kolla-push-images
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-discover
            linaro:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 30
    parameters:
        - file:
            name: push.parameters
            description: "tag of images to push"
    disabled: false
    node: leg-aarch64
    concurrent: false
    display-name: 'LEG Kolla images publish'
    wrappers:
        - timestamps
        - copy-to-slave:
            includes:
                - config.json
            relative-to: 'somewhereElse'
        - credentials-binding:
            - text:
                credential-id: DOCKER_AUTH
                variable: DOCKER_AUTH
    builders:
        - shell:
            !include-raw: leg-kolla-push-images/build.sh
        - trigger-builds:
            - project:
                - 'leg-kolla-remove-images'
              property-file: "remove.parameters"
    publishers:
        - email:
            recipients: 'marcin.juszkiewicz@linaro.org riku.voipio@linaro.org fathi.boudra@linaro.org ldcg-team@linaro.org'
