- job:
    name: linaro-art-build-metrics
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-discover
            linaro-android-builders:
                - job-build
                - job-read
                - job-extended-read
                - job-workspace
            linaro-art:
                - job-build
                - job-read
                - job-extended-read
                - job-workspace
        - build-discarder:
            days-to-keep: 60
            num-to-keep: 60
    disabled: false
    node: docker-bionic-art
    display-name: 'ART: Build Metrics'
    concurrent: true
    wrappers:
        - timestamps
        - timeout:
            timeout: 200
        - credentials-binding:
            - text:
                credential-id: ART_METRICS_TOKEN
                variable: ART_METRICS_TOKEN
    builders:
        - shell: |
            #!/bin/bash
            rm -rf art-build-tests android
            #set -xe

            git clone git://git.linaro.org/people/vishal.bhoj/art-build-tests.sh.git art-build-tests
            cd art-build-tests/job-metrics/
            sudo sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install -y xml-twig-tools bc
            . ./metrics.sh ${ART_METRICS_TOKEN}
            cat results.txt
    publishers:
        - email-ext:
            recipients: 'linaro-art@linaro.org'
            content-type: text
            subject: 'Build Time statistics for ART CI Jobs'
            body: |
                Build URL: ${PROJECT_URL}${BUILD_NUMBER}/
                Full log: ${PROJECT_URL}${BUILD_NUMBER}/consoleText
                ${BUILD_LOG_REGEX, regex=".*Build Time.*", linesBefore=0, linesAfter=0, showTruncatedLines=false}
            always: true
