- job:
    name: openembedded-lkft-dlezcano-4.14
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 30
    parameters:
        - string:
            name: KERNEL_BRANCH
            default: 'lkft'
        - string:
            name: KERNEL_VERSION
            default: '4.14'
        - string:
            name: KERNEL_ARCH
            default: 'arm64'
        - string:
            name: KERNEL_CONFIG
            default: 'defconfig'
        - string:
            name: KERNEL_RECIPE
            default: 'linux-generic'
        - string:
            name: KERNEL_REPO
            default: 'https://git.linaro.org/people/daniel.lezcano/android.git'
        - string:
            name: KERNEL_DESCRIBE
        - string:
            name: KERNEL_COMMIT
        - string:
            name: MAKE_KERNELVERSION
        - string:
            name: IMAGES
            default: 'rpb-console-image-lkft'
        - string:
            name: MANIFEST_BRANCH
            default: 'rocko'
        - string:
            name: PUB_DEST
            default: 'openembedded/lkft/${MANIFEST_BRANCH}/dlezcano-hikey/${DISTRO}/${KERNEL_VERSION}/${BUILD_NUMBER}'
        - string:
            name: LAVA_SERVER
            default: 'https://lkft.validation.linaro.org/RPC2/'
        - string:
            name: QA_SERVER
            default: 'https://qa-reports.linaro.org'
        - string:
            name: QA_SERVER_PROJECT
            default: 'android-hikey-dlezcano-4.14-oe'
        - string:
            name: QA_SERVER_TEAM
            default: 'people'
        - string:
            name: SKIP_LAVA
            default: ''
        - string:
            name: LAVA_JOB_PRIORITY
            default: 'medium'
        - string:
            name: MACHINE
            default: 'hikey'
        - string:
            name: DISTRO
            default: 'rpb'
    disabled: true
    node: docker-stretch-amd64
    display-name: 'LKFT - AOSP 4.14/dlezcano (OpenEmbedded/rocko)'
    axes:
    wrappers:
        - timeout:
            timeout: 180
        - timestamps
        - ssh-agent-credentials:
            users:
                - 'OE_COMMIT_BOT_KEY'
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: QA_REPORTS_TOKEN
    builders:
        - shell: |
            #!/bin/bash

            # Mapping for MACHINE -> DEVICE_TYPE
            case "${MACHINE}" in
              hikey)
                DEVICE_TYPE=hi6220-hikey
                ;;
            esac

            cat << EOF > ${WORKSPACE}/custom-kernel-info.inc.tmp
            KERNEL_COMMIT = "${KERNEL_COMMIT}"
            KERNEL_REPO = "${KERNEL_REPO/http*:/git:}"
            KERNEL_BRANCH = "${KERNEL_BRANCH}"
            KERNEL_CONFIG_aarch64 = "${KERNEL_CONFIG}"
            KERNEL_CONFIG_arm = "${KERNEL_CONFIG}"
            KERNEL_CONFIG_x86-64 = "${KERNEL_CONFIG}"
            EOF

            echo "IMAGES=rpb-console-image" > parameters
            echo "MANIFEST_URL=https://github.com/96boards/oe-rpb-manifest.git" >> parameters
            echo "MANIFEST_BRANCH=${MANIFEST_BRANCH}" >> parameters
            echo "DISTRO=rpb" >> parameters
            echo "MACHINE=${MACHINE}" >> parameters
            echo "DEVICE_TYPE=${DEVICE_TYPE}" >> parameters
            cat parameters

            echo "#${BUILD_NUMBER}-${KERNEL_COMMIT:0:8}" > ${WORKSPACE}/version.txt

        - build-name-setter:
            name: 'version.txt'
            file: true
        - inject:
            properties-file: parameters
        - shell:
            !include-raw: openembedded-lkft/builders-generic.sh
        - inject:
            properties-file: post_build_lava_parameters
        - linaro-publish-token
        - shell:
            !include-raw: openembedded-lkft/publishers.sh
        - shell:
            !include-raw: openembedded-lkft/submit_for_testing.sh
    publishers:
        - groovy-postbuild:
            script:
                !include-raw:
                  - rpb-openembedded/postbuild.groovy
                  - openembedded-lkft/postbuild.groovy
        - email-ext:
            recipients: 'daniel.lezcano@linaro.org'
            matrix-trigger: only-configurations
            subject: '[CI] ${MACHINE}: ${KERNEL_BRANCH} {{SRCREV_kernel}} ${BUILD_STATUS}'
            body: |
                Build URL: ${PROJECT_URL}${BUILD_NUMBER}/
                Full log: ${PROJECT_URL}${BUILD_NUMBER}/consoleText
                Parsed warnings/errors: ${PROJECT_URL}${BUILD_NUMBER}/parsed_console
                Git branch: ${KERNEL_BRANCH}
                Git URL: ${KERNEL_REPO}
                Git commit: ${KERNEL_COMMIT}

                Errors:
                ${BUILD_LOG_REGEX, regex="^ERROR:.* ", linesBefore=0, linesAfter=0, showTruncatedLines=false}
            presend-script:
                !include-raw: openembedded-lkft/presend-script.groovy
