- job:
    name: openembedded-osf-linux-microplatform
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 30
            artifact-num-to-keep: 1
    parameters:
        - string:
            name: PUB_DEST
            default: 'openembedded/${JOB_NAME}/${BUILD_NUMBER}'
        - string:
            name: IMAGES
            default: 'lmp-gateway-image'
        - string:
            name: LAVA_SERVER
            default: 'https://validation.linaro.org/RPC2/'
        - string:
            name: QA_SERVER
            default: 'https://qa-reports.linaro.org'
        - string:
            name: BASELINE_SHA
            default: 'cf184b1a123026ec9f12c5fdd75a0c3d945a86c7f9408aaeffa257d68d31e620'
        - string:
            name: QA_SERVER_TEAM
            default: 'ledge'
        - string:
            name: QA_SERVER_PROJECT
            default: 'microplatform-prototype'
        - string:
            name: SKIP_LAVA
            default: ''
        - string:
            name: LAVA_JOB_PRIORITY
            default: 'medium'

    disabled: false
    node: docker-xenial-amd64
    display-name: 'OSF Linux Microplatform Builder'
    wrappers:
        - timeout:
            timeout: 180
        - timestamps
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: QA_REPORTS_TOKEN
    builders:
        - shell:
            !include-raw: osf-linux-microplatform/builders.sh
        - linaro-publish-token
        - inject:
            properties-file: post_build_lava_parameters
        - shell:
            !include-raw: rpb-openembedded/publishers.sh
        - shell:
            !include-raw: osf-linux-microplatform/submit_for_testing.sh
    publishers:
        - trigger-parameterized-builds:
            - project:
                - 'ostree-publish-ota'
              condition: SUCCESS
              property-file: ota_params
        - groovy-postbuild:
            script:
                !include-raw:
                  - rpb-openembedded/postbuild.groovy
