- job:
    name: qa-test-definitions-sanity-check
    project-type: freestyle
    defaults: global
    logrotate:
        daysToKeep: 30
        numToKeep: 30
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
    disabled: false
    node: docker-stretch-amd64
    display-name: 'QA test definitions sanity check'
    triggers:
        - gerrit:
            server-name: 'review.linaro.org'
            override-votes: true
            gerrit-build-successful-verified-value: 1
            gerrit-build-failed-verified-value: -1
            gerrit-build-successful-codereview-value: 1
            gerrit-build-failed-codereview-value: -1
            readable-message: true
            successful-message: 'Sanity check OK'
            failure-message: '[OUTPUT]:'
            failure-message-file: 'build-error.txt'
            trigger-for-unreviewed-patches: true
            projects:
                - project-compare-type: 'ANT'
                  project-pattern: 'qa/test-definitions'
                  branches:
                    - branch-compare-type: 'ANT'
                      branch-pattern: 'master'
    wrappers:
        - timestamps
    builders:
        - shell: |
            #!/bin/bash

            set -ex

            sudo apt-get update
            sudo apt-get install -y shellcheck python3-pycodestyle python3-yaml php-cli

            echo ""
            echo "########################################################################"
            echo "    Gerrit Environment"
            env |grep GERRIT
            echo "########################################################################"

            echo "#${BUILD_NUMBER}-${GERRIT_PATCHSET_REVISION:0:8}" > ${WORKSPACE}/version.txt

            git clone -b ${GERRIT_BRANCH} --depth 1 https://git.linaro.org/${GERRIT_PROJECT}
            cd $(basename ${GERRIT_PROJECT})
            git fetch https://review.linaro.org/${GERRIT_PROJECT} ${GERRIT_REFSPEC}
            git checkout -q FETCH_HEAD

            python3 validate.py -r ${WORKSPACE}/build-error.txt -g -s SC1091
        - build-name-setter:
            name: 'version.txt'
            file: true
