- job:
    name: qemu-lava-risu
    project-type: matrix
    defaults: global
    logrotate:
        daysToKeep: 30
        numToKeep: 30
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
    disabled: false
    node: build
    child-workspace: .
    display-name: 'QEMU - run LAVA based RISU tests against OBS build'
    axes:
        - axis:
            type: user-defined
            name: TARGET
            values:
                - aarch64
    execution-strategy:
        sequential: true
    triggers:
        - pollurl:
            cron: '@hourly'
            polling-node: build
            urls:
              - url: 'http://obs.linaro.org/linaro-staging-stretch/Debian_9.0/Release'
                check-content:
                  - simple: true
    wrappers:
        - timestamps
        - matrix-tie-parent:
            node: build
    builders:
        - shell: |
            #!/bin/bash

            cat << EOF > post_build_lava_parameters
            DEVICE_TYPE=kvm
            CUSTOM_YAML_URL=https://git.linaro.org/people/alex.bennee/test-runners.git/blob_plain/HEAD:/qemu-master-${TARGET}-user-risu.yaml
            EOF
        - trigger-builds:
            - project: 'post-build-lava'
              property-file: post_build_lava_parameters
              block: true
