- job:
    name: qemu-docker
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
            linaro:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 7
            num-to-keep: 7
    disabled: false
    node: docker-xenial
    display-name: 'QEMU source package build'
    scm:
        - git:
            url: git://git.qemu.org/qemu.git
            refspec: +refs/heads/master:refs/remotes/origin/master
            name: origin
            branches:
                - refs/heads/master
            basedir: qemu-linaro
            skip-tag: true
            clean: true
            disable-submodules: true
            wipe-workspace: false
    wrappers:
        - timestamps
        - build-name:
            name: '#${BUILD_NUMBER}-${GIT_REVISION,length=8}'
    builders:
        - shell: |
            #!/bin/bash

            set -e

            rm -rf qemu-ci
            git clone --depth 1 http://git.linaro.org/git/ci/qemu.git qemu-ci
            bash -x qemu-ci/qemu-pkg.sh
    publishers:
        - archive:
            artifacts: '*.changes, *.dsc, *.gz, *.bz2, *.xz'
            latest-only: true
# Disable LAVA job submissions temporarily
# until the jobs have been updated from LAVA v1 to v2
#       - trigger:
#           project: 'qemu-lava-ltp-tests, qemu-lava-tcg-system'
        - trigger-parameterized-builds:
            - project: build-package-obs
              property-file: qemu-params
              condition: SUCCESS
        - email:
            recipients: 'riku.voipio@linaro.org'
