- job:
    name: sumits-oe
    project-type: matrix
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
                - job-workspace
            linaro:
                - job-read
                - job-extended-read
                - job-build
                - job-cancel
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 30
            artifact-num-to-keep: 1
    parameters:
        - string:
            name: KERNEL_BRANCH
            default: 'hikey-new-rebase-trial'
            description: '<font color="red"><b>[mandatory]</b></font> git branch to use'
        - string:
            name: KERNEL_VERSION
            default: '4.4'
            description: '<font color="red"><b>[mandatory]</b></font> kernel version to use, matching the kernel used'
        - string:
            name: KERNEL_RECIPE
            default: 'linux-generic-lts'
            description: '<font color="red"><b>[mandatory]</b></font> kernel recipe to use, matching the kernel version'
        - string:
            name: KERNEL_REPO
            default: 'https://git.linaro.org/people/sumit.semwal/linux-3.x.git'
            description: '<font color="red"><b>[mandatory]</b></font> git repository to use'
        - string:
            name: KERNEL_DESCRIBE
        - string:
            name: SRCREV_kernel
            description: '<font color="red"><b>[mandatory]</b></font> git commit to use'
        - string:
            name: MAKE_KERNELVERSION
        - string:
            name: IMAGES
            default: 'rpb-console-image'
        - string:
            name: MANIFEST_BRANCH
            default: 'morty'
        - string:
            name: PUB_DEST
            default: 'people/sumits/oe/${MANIFEST_BRANCH}/${MACHINE}/${DISTRO}/${KERNEL_VERSION}/${BUILD_NUMBER}'
            description: '<font color="red"><b>[mandatory]</b></font> publishing destination path'
        - string:
            name: LAVA_SERVER
            default: 'https://lkft.validation.linaro.org/RPC2/'
        - string:
            name: QA_SERVER
            default: 'https://qa-reports.linaro.org'
        - string:
            name: QA_SERVER_PROJECT
            default: 'linaro-hikey-stable-4.4-oe'
        - string:
            name: SKIP_LAVA
            default: '1'
        - string:
            name: LAVA_JOB_PRIORITY
            default: 'low'
    disabled: false
    node: master
    display-name: 'Sumit Semwal (OpenEmbedded/morty)'
    axes:
        - axis:
            type: user-defined
            name: MACHINE
            values:
                - 'hikey'
        - axis:
            type: user-defined
            name: DISTRO
            values:
                - rpb
        - axis:
            type: slave
            name: label
            values:
                - docker-stretch-amd64
    execution-strategy:
        sequential: false
    wrappers:
        - timestamps
        - ssh-agent-credentials:
            users:
                - 'OE_COMMIT_BOT_KEY'
        - credentials-binding:
            - text:
                credential-id: QA_REPORTS_TOKEN
                variable: QA_REPORTS_TOKEN
    builders:
        - shell: |
            #!/bin/bash

            # Mapping for MACHINE -> DEVICE_TYPE
            case "${MACHINE}" in
              hikey)
                DEVICE_TYPE=hi6220-hikey
                ;;
            esac

            echo "DEVICE_TYPE=${DEVICE_TYPE}" > device_type_parameters

            if [ -z "${SRCREV_kernel}" ]; then
              SRCREV_kernel=$(git ls-remote --heads ${KERNEL_REPO} ${KERNEL_BRANCH} | cut -f1)
            fi

            echo "#${BUILD_NUMBER}-${SRCREV_kernel:0:8}" > ${WORKSPACE}/version.txt
        - build-name-setter:
            name: 'version.txt'
            file: true
        - inject:
            properties-file: device_type_parameters
        - shell:
            !include-raw: openembedded-lkft/builders-sumits.sh
        - inject:
            properties-file: post_build_lava_parameters
        - linaro-publish-token
        - shell: |
            #!/bin/bash

            # Publish
            test -d ${HOME}/bin || mkdir ${HOME}/bin
            wget -q https://git.linaro.org/ci/publishing-api.git/blob_plain/HEAD:/linaro-cp.py -O ${HOME}/bin/linaro-cp.py
            time python3 ${HOME}/bin/linaro-cp.py \
              --server ${PUBLISH_SERVER} \
              --link-latest \
              ${DEPLOY_DIR_IMAGE}/ ${PUB_DEST}
        - shell:
            !include-raw: openembedded-lkft/submit_for_testing.sh
    publishers:
        - groovy-postbuild:
            script:
                !include-raw:
                  - rpb-openembedded/postbuild.groovy
                  - openembedded-lkft/postbuild.groovy
        - email-ext:
            recipients: 'sumit.semwal@linaro.org'
            matrix-trigger: only-configurations
            subject: '[CI] ${MACHINE}: ${KERNEL_BRANCH} {{SRCREV_kernel}} ${BUILD_STATUS}'
            body: |
                Build URL: ${PROJECT_URL}${BUILD_NUMBER}/
                Full log: ${PROJECT_URL}${BUILD_NUMBER}/consoleText
                Parsed warnings/errors: ${PROJECT_URL}${BUILD_NUMBER}/parsed_console
                Git branch: ${KERNEL_BRANCH}
                Git URL: ${KERNEL_REPO}
                Git commit: ${SRCREV_kernel}

                Errors:
                ${BUILD_LOG_REGEX, regex="^ERROR:.* ", linesBefore=0, linesAfter=0, showTruncatedLines=false}
            presend-script:
                !include-raw: openembedded-lkft/presend-script.groovy
