- job:
    name: trigger-khilman-buildroot
    project-type: freestyle
    defaults: global
    logrotate:
        daysToKeep: 30
        numToKeep: 30
    properties:
        - authorization:
            anonymous:
                - job-read
    disabled: false
    node: build
    display-name: 'Trigger for khilman - Buildroot'
    scm:
        - git:
            url: https://github.com/kernelci/buildroot.git
            refspec: +refs/heads/kernelci/latest:refs/remotes/origin/kernelci/latest
            name: origin
            branches:
                - refs/heads/kernelci/latest
            skip-tag: true
            shallow-clone: true
            wipe-workspace: false
    triggers:
        - pollscm: 'H/5 * * * *'
    wrappers:
        - timestamps
        - build-name:
            name: '#${BUILD_NUMBER}-${GIT_REVISION,length=8}'
    builders:
        - trigger-builds:
            - project: 'khilman-buildroot'
