device_type: db410c-android
job_name: db410c-android

timeouts:
  job:
    minutes: 540
  action:
    minutes: 15
  connection:
    minutes: 2
priority: medium
visibility: public

metadata:
  android.build: "${BUILD_NUMBER}"
  android.name: "${JOB_NAME}"
  android.url: "${BUILD_URL}"
  git branch: "${KERNEL_BRANCH}"
  git repo: "${KERNEL_REPO}"
  git commit: "${KERNEL_COMMIT}"
  git describe: "${KERNEL_DESCRIBE}"
  build-url: "${BUILD_URL}"
  series: qcomlt

protocols:
  lava-lxc:
    name: lxc-db410c-test
    distribution: ubuntu
    release: xenial
    arch: amd64
    verbose: true

actions:
- deploy:
    namespace: tlxc
    timeout:
      minutes: 15
    to: lxc
    packages:
    - wget
    - unzip
    os: debian

- boot:
    namespace: tlxc
    prompts:
    - root@(.*):/#
    - :/
    timeout:
      minutes: 5
    method: lxc

- test:
    namespace: tlxc
    timeout:
      minutes: 10
    definitions:
    - repository: https://git.linaro.org/qa/test-definitions.git
      from: git
      path: automated/linux/android-platform-tools/install.yaml
      name: install-android-platform-tools-r2600
      parameters:
        LINK: 'https://dl.google.com/android/repository/platform-tools_r26.0.0-linux.zip'

- deploy:
    timeout:
      minutes: 15
    to: fastboot
    namespace: droid
    images:
      boot:
        url: ${DOWNLOAD_URL}/boot-db410c.img
      system:
        url: ${REFERENCE_BUILD_URL}/system.img
      userdata:
        url: ${REFERENCE_BUILD_URL}/userdata.img
      cache:
        url: ${REFERENCE_BUILD_URL}/cache.img
    os: debian
    protocols:
      lava-lxc:
      - action: fastboot-deploy
        request: pre-power-command
        timeout:
          minutes: 2

- boot:
    namespace: droid
    prompts:
    - root@(.*):/#
    - :/
    timeout:
      minutes: 15
    method: fastboot
