actions:
- command: deploy_linaro_image
  parameters:
    dtb: 'omap4-panda-es.dtb'
    hwpack: '${HWPACK_BUILD_URL}'
    rootfs: '${ROOTFS_BUILD_URL}'
  metadata:
    build id: '${BUILD_NUMBER}'
    defconfig: '${defconfig}'
    git URL: '${GIT_URL}'
    git branch: '${GIT_BRANCH}'
    git commit: '${GIT_COMMIT}'
- command: lava_test_shell
  parameters:
    testdef_repos:
    - git-repo: git://git.linaro.org/qa/test-definitions.git
      testdef: ubuntu/pwrmgmt.yaml
    timeout: 1200
- command: lava_test_shell
  parameters:
    testdef_repos:
    - git-repo: git://git.linaro.org/qa/test-definitions.git
      testdef: ubuntu/smoke-tests-basic.yaml
    timeout: 1200
- command: submit_results
  parameters:
    server: 'http://${LAVA_SERVER}'
    stream: '${BUNDLE_STREAM_NAME}'
device_type: '${DEVICE_TYPE}'
job_name: '${BUILD_URL}'
timeout: 3600